### ISSUE TITLE
Import error when using node + tsc

### ISSUE THREAD

**Issue by ex-daniel-graupner** [ventojs/vento#174]
I installed ventojs via npm. My project uses nodejs v22.17 and typescript.

tsconfig includes the following compiler options:
```json
{
  "compilerOptions": {
    "declaration": false,
    "importHelpers": true,
    "module": "Node16",
    "moduleResolution": "node16",
    "target": "es2022",
    "outDir": "dist",
    "rootDir": ".",
    "strict": true,
    "esModuleInterop": true,
    "sourceMap": true,
    "forceConsistentCasingInFileNames": true
  }
```

I just added file VentoTest.ts with one line: `import vento from "ventojs"`.

Compiling with tsc throws errors:
```
node_modules/ventojs/types/core/environment.d.ts:1:23 - error TS2846: A declaration file cannot be imported without 'import type'. Did you mean to import an implementation file './tokenizer.js' instead?

1 import { Token } from "./tokenizer.d.ts";
                        ~~~~~~~~~~~~~~~~~~

node_modules/ventojs/types/mod.d.ts:1:42 - error TS2846: A declaration file cannot be imported without 'import type'. Did you mean to import an implementation file './core/environment.js' instead?

1 import { Environment, type Loader } from "./core/environment.d.ts";
                                           ~~~~~~~~~~~~~~~~~~~~~~~~~
```

How can I use ventojs with node + typescript?

**Comment by ex-daniel-graupner** [comment]
Thanks for your support.

The project I am working on is quite old and does not use the native TS support. I might consider this but at the moment it works still fine using the typescript compiler. Running typescript natively with node seems to have limitations.

Unfortunately, setting `verbatimModuleSyntax` to false does not help, I get the same error messages.
I am using several dependencies, with and without TS types they work fine but I do not really understand how ventojs is different.

**Comment by oscarotero** [comment]
Ok, it should work fine in the new version (2.3.1)

**Comment by ex-daniel-graupner** [comment]
Great, thank you.
